### ISSUE TITLE
Issue on page /chapter_overview/Part2.html 添加参考书

### ISSUE THREAD

**Issue by nubbygit** [hcp4715/PyBayesianBook#10]
在该段课程讲述中所提到的基于贝叶斯的认知建模的书籍是Wagenmakers的“Bayesian Cognitive Modeling_ A Practical Course”，书籍详情链接如下：https://www.amazon.com/Bayesian-Cognitive-Modeling-Practical-Course/dp/1107018455

**Comment by hcp4715** [comment]
@nubbygit  我们已经在相关章节添加本推荐的书目
